import { useEffect, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { ArrowRight, ChevronDown, ChevronUp, CloudOff, Home, Pencil, Plus, Save, ShieldCheck, Trash2 } from 'lucide-react'
import { Modal } from '../components/Modal'
import { TaskForm, type TaskFormData } from '../components/TaskForm'
import { db, markSyncChange, todayKey, tomorrowKey, uid } from '../db'
import { defaultSyncSettings, getSyncSettings, saveSyncSettings, saveTomorrowPlan, syncHome } from '../syncService'
import type { Capture, DayPlan, SyncSettings, Task } from '../types'

export function EndDayView({ allTasks, captures, refresh }: { allTasks: Task[]; captures: Capture[]; refresh: () => void }) {
  const todayPlan = useLiveQuery(() => db.dayPlans.get(todayKey()))
  const tomorrowPlan = useLiveQuery(() => db.dayPlans.get(tomorrowKey()))
  const pending = useLiveQuery(() => db.syncChanges.count(), [], 0) ?? 0
  const [note, setNote] = useState(''); const [editing, setEditing] = useState<Task | null | undefined>(undefined)
  const [settings, setSettings] = useState<SyncSettings>(defaultSyncSettings); const [showSettings, setShowSettings] = useState(false); const [syncing, setSyncing] = useState(false); const [message, setMessage] = useState('')
  useEffect(() => { if (todayPlan) setNote(todayPlan.endOfDayNote ?? '') }, [todayPlan])
  useEffect(() => { getSyncSettings().then(setSettings) }, [])
  const todayTasks = (todayPlan?.taskIds ?? []).map(id => allTasks.find(t => t.id === id)).filter((t): t is Task => Boolean(t))
  const tomorrowTasks = (tomorrowPlan?.taskIds ?? []).map(id => allTasks.find(t => t.id === id)).filter((t): t is Task => Boolean(t)).sort((a,b) => a.order-b.order)
  const completed = todayTasks.filter(t => t.status === 'completed'), blocked = todayTasks.filter(t => t.status === 'blocked'), unfinished = todayTasks.filter(t => !['completed','blocked'].includes(t.status))
  const ensureTomorrowPlan = async (taskIds: string[]) => { const existing = await db.dayPlans.get(tomorrowKey()); await db.dayPlans.put({ date: tomorrowKey(), workWins: existing?.workWins ?? '', taskIds }); await markSyncChange('dayPlan', tomorrowKey()) }
  const saveTask = async (data: TaskFormData) => { if (editing) { await db.tasks.update(editing.id, data); await markSyncChange('task', editing.id) } else { const task: Task = { id: uid(), ...data, notes: data.notes ?? '', plannedDate: tomorrowKey(), status: 'planned', order: tomorrowTasks.length }; await db.tasks.add(task); await ensureTomorrowPlan([...(tomorrowPlan?.taskIds ?? []), task.id]); await markSyncChange('task', task.id) } setEditing(undefined); refresh() }
  const removeTomorrow = async (task: Task) => { await db.tasks.delete(task.id); await ensureTomorrowPlan((tomorrowPlan?.taskIds ?? []).filter(id => id !== task.id)); await markSyncChange('task', task.id); refresh() }
  const move = async (task: Task, delta: number) => { const index = tomorrowTasks.findIndex(t => t.id === task.id), other = tomorrowTasks[index + delta]; if (!other) return; await db.transaction('rw', db.tasks, async () => { await db.tasks.update(task.id, { order: other.order }); await db.tasks.update(other.id, { order: task.order }) }); await markSyncChange('task', task.id); await markSyncChange('task', other.id); refresh() }
  const carry = async (task: Task) => { if (tomorrowTasks.some(item => item.sourceTaskId === task.id)) return; const copy: Task = { ...task, id: uid(), sourceTaskId: task.id, plannedDate: tomorrowKey(), status: 'planned', order: tomorrowTasks.length, actualStart: undefined, actualEnd: undefined }; await db.tasks.add(copy); await ensureTomorrowPlan([...(tomorrowPlan?.taskIds ?? []), copy.id]); await markSyncChange('task', copy.id); refresh() }
  const doSync = async () => { if (!settings.endpoint || !settings.token) { setShowSettings(true); return } setSyncing(true); setMessage(''); try { await saveSyncSettings(settings); await syncHome(settings); const fresh = await getSyncSettings(); setSettings(fresh); setMessage('SYNCED'); refresh() } catch { const fresh = await getSyncSettings(); setSettings(fresh); setMessage('SERA UNAVAILABLE — everything is still safe on this tablet.') } finally { setSyncing(false) } }
  const lastSync = settings.lastSuccessfulSync ? new Intl.DateTimeFormat('en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(settings.lastSuccessfulSync)) : 'Not synced yet'
  return <main className="page end-day-view"><div className="page-header"><div><p className="eyebrow">END DAY</p><h1>Set tomorrow down gently.</h1><p>Everything stays on this tablet until you choose Sync Home.</p></div></div>
    <section className="sync-home-card"><div className="sync-title"><Home/><div><p className="eyebrow">PRIVATE HOME SYNC</p><h2>Sync Home</h2></div><span className={`reachability ${settings.lastReachable === true ? 'reachable' : settings.lastReachable === false ? 'unreachable' : ''}`}>{settings.lastReachable === true ? 'SERA REACHABLE' : settings.lastReachable === false ? 'SERA UNAVAILABLE' : 'NOT CHECKED'}</span></div><div className="sync-facts"><div><strong>{pending}</strong><span>changes waiting</span></div><div><strong>{lastSync}</strong><span>last successful sync</span></div></div>{message && <p className="sync-message">{message}</p>}<div className="sync-actions"><button className="button ghost" onClick={() => setShowSettings(true)}>Connection settings</button><button className="button sync-button" disabled={syncing} onClick={doSync}><ShieldCheck/>{syncing ? 'Connecting privately…' : 'Sync Home'}</button></div></section>
    <div className="end-summary"><Summary title="Completed today" tasks={completed}/><Summary title="Unfinished / carry-over" tasks={unfinished} action={task => <button onClick={() => carry(task)}><ArrowRight/> Carry to tomorrow</button>}/><Summary title="Blocked" tasks={blocked}/><section className="end-panel"><h2>Captures</h2>{captures.length ? captures.map(c => <p key={c.id} className={c.handled?'muted':''}>{c.text}</p>) : <p className="muted">No captures today.</p>}</section></div>
    <section className="tomorrow-section"><div className="tomorrow-heading"><div><p className="eyebrow">TOMORROW</p><h2>Task queue</h2></div><button className="button primary" onClick={() => setEditing(null)}><Plus/> Add tomorrow task</button></div><div className="tomorrow-list">{tomorrowTasks.length ? tomorrowTasks.map((task,index) => <article key={task.id}><div className="reorder"><button disabled={index===0} onClick={()=>move(task,-1)}><ChevronUp/></button><button disabled={index===tomorrowTasks.length-1} onClick={()=>move(task,1)}><ChevronDown/></button></div><div><strong>{task.title}</strong><span>{task.category} · {task.estimatedMinutes} min</span></div><button aria-label="Edit tomorrow task" onClick={()=>setEditing(task)}><Pencil/></button><button aria-label="Delete tomorrow task" onClick={()=>removeTomorrow(task)}><Trash2/></button></article>) : <div className="empty-state"><p>Tomorrow is open. Add one clear first step when you’re ready.</p></div>}</div></section>
    <section className="sera-note"><label>Short note for Sera<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Anything tomorrow-you should know?"/></label><button className="button save-tomorrow" onClick={async()=>{await saveTomorrowPlan(note);setMessage('Saved locally for tomorrow.');refresh()}}><Save/> Save for tomorrow</button><p><CloudOff/> Saved locally. No network connection required.</p></section>
    {editing !== undefined && <Modal title={editing ? 'Edit tomorrow task' : 'Add tomorrow task'} onClose={()=>setEditing(undefined)}><TaskForm task={editing ?? undefined} onSubmit={saveTask} onCancel={()=>setEditing(undefined)} submitLabel={editing?'Save changes':'Add to tomorrow'}/></Modal>}
    {showSettings && <Modal title="Private Sera connection" onClose={()=>setShowSettings(false)}><form onSubmit={async e=>{e.preventDefault();await saveSyncSettings(settings);setShowSettings(false)}}><p className="settings-help">Use the HTTPS address provided by Tailscale Serve. The token stays only in this tablet’s IndexedDB.</p><label>Sera HTTPS address<input type="url" required placeholder="https://sera.your-tailnet.ts.net" value={settings.endpoint} onChange={e=>setSettings({...settings,endpoint:e.target.value})}/></label><label>Bearer token<input type="password" required autoComplete="off" value={settings.token} onChange={e=>setSettings({...settings,token:e.target.value})}/></label><div className="form-actions"><button type="button" className="button ghost" onClick={()=>setShowSettings(false)}>Cancel</button><button className="button primary">Save locally</button></div></form></Modal>}
  </main>
}

function Summary({title,tasks,action}:{title:string;tasks:Task[];action?:(task:Task)=>React.ReactNode}) { return <section className="end-panel"><h2>{title}<span>{tasks.length}</span></h2>{tasks.length ? tasks.map(task=><div className="summary-task" key={task.id}><strong>{task.title}</strong>{action?.(task)}</div>) : <p className="muted">Nothing here.</p>}</section> }
