import { useState } from 'react'
import { ChevronDown, ChevronUp, Clock3, Edit3, Plus, Trash2 } from 'lucide-react'
import { db } from '../db'; import { createTask } from '../taskService'; import type { Task } from '../types'; import { Modal } from '../components/Modal'; import { TaskForm, type TaskFormData } from '../components/TaskForm'
export function PlanView({ tasks, refresh }: { tasks: Task[]; refresh: () => void }) {
 const [editing, setEditing] = useState<Task|null|undefined>(undefined); const ordered = [...tasks].sort((a,b)=>a.order-b.order)
 const save = async (d: TaskFormData) => { if(editing) await db.tasks.update(editing.id,d); else await createTask(d); setEditing(undefined); refresh() }
 const move = async (task: Task, delta: number) => { const i=ordered.findIndex(t=>t.id===task.id), other=ordered[i+delta]; if(!other)return; await db.transaction('rw',db.tasks,async()=>{ await db.tasks.update(task.id,{order:other.order}); await db.tasks.update(other.id,{order:task.order})}); refresh() }
 return <main className="page plan-view"><div className="page-header"><div><p className="eyebrow">PLAN</p><h1>Shape the path ahead.</h1><p>Keep it light. This is guidance, not a promise.</p></div><button className="button primary" onClick={()=>setEditing(null)}><Plus/> Add task</button></div>
 <div className="task-list">{ordered.length ? ordered.map((t,i)=><article className={`task-row status-${t.status}`} key={t.id}><div className="reorder"><button aria-label="Move up" disabled={i===0} onClick={()=>move(t,-1)}><ChevronUp/></button><button aria-label="Move down" disabled={i===ordered.length-1} onClick={()=>move(t,1)}><ChevronDown/></button></div><div className="task-info"><div className="task-title-line"><h3>{t.title}</h3><span className={`priority ${t.priority}`}>{t.priority}</span></div><p>{t.category} <span>·</span> <Clock3/> {t.estimatedMinutes} min {t.plannedStart && <><span>·</span> around {t.plannedStart}</>}</p></div><span className="status-label">{t.status}</span><div className="row-actions"><button onClick={()=>setEditing(t)} aria-label={`Edit ${t.title}`}><Edit3/></button><button onClick={async()=>{if(confirm(`Delete “${t.title}”?`)){await db.tasks.delete(t.id);refresh()}}} aria-label={`Delete ${t.title}`}><Trash2/></button></div></article>) : <div className="empty-state"><h2>No tasks planned yet.</h2><p>Add one clear next step. You can always adjust later.</p></div>}</div>
 {editing !== undefined && <Modal title={editing ? 'Edit task' : 'Add a task'} onClose={()=>setEditing(undefined)}><TaskForm task={editing ?? undefined} onSubmit={save} onCancel={()=>setEditing(undefined)} submitLabel={editing?'Save changes':'Add to today'}/></Modal>}</main>
}
