import { useEffect, useMemo, useState } from 'react'
import { Ban, Check, CirclePause, Inbox, Play, RotateCcw, Sparkles } from 'lucide-react'
import type { ResetDuration, Task } from '../types'
import { addCapture, blockTask, completeTask, interruptTask, resumeTask, startTask } from '../taskService'
import { Modal } from '../components/Modal'
import { ResetExperience } from '../components/ResetExperience'
import { CompletionCelebration } from '../components/CompletionCelebration'

const elapsed = (iso?: string, tick = 0) => { if (!iso) return 'Ready when you are'; const mins = Math.max(0, Math.floor((Date.now() - new Date(iso).getTime()) / 60000)); return `${Math.floor(mins / 60).toString().padStart(2,'0')}:${(mins % 60).toString().padStart(2,'0')} elapsed` }
export function TodayView({ tasks, refresh, openCapture }: { tasks: Task[]; refresh: () => void; openCapture: () => void }) {
  const [tick, setTick] = useState(0); const [modal, setModal] = useState<'interrupt'|'block'|'capture'|null>(null); const [note, setNote] = useState('')
  const [reset, setReset] = useState<{ task?: Task; fromInterruption: boolean; initialDuration?: ResetDuration; startImmediately: boolean }>(); const [celebration,setCelebration]=useState<Task>()
  useEffect(() => { const id = setInterval(() => setTick(x => x + 1), 30000); return () => clearInterval(id) }, [])
  const current = useMemo(() => tasks.find(t => ['active','interrupted'].includes(t.status)), [tasks]); const next = tasks.find(t => t.status === 'planned')
  const date = new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())
  const act = async (fn: () => Promise<unknown>) => { await fn(); setModal(null); setNote(''); refresh() }
  return <main className="today-view page"><div className="day-intro"><p className="eyebrow">TODAY · {date}</p><h1>{current?.status === 'interrupted' ? 'Your place is saved.' : current ? 'Just this, for now.' : next ? 'Let’s begin gently.' : 'Your day is clear.'}</h1></div>
    <section className={`now-card ${current?.status === 'interrupted' ? 'paused' : ''}`}>
      <div className="now-label"><span>NOW</span>{current && <span className="category-pill">{current.category}</span>}</div>
      {current ? <><h2>{current.title}</h2>{current.notes && <p className="task-note">{current.notes}</p>}<div className="timer">{current.status === 'interrupted' ? 'Paused — come back when ready' : elapsed(current.actualStart, tick)}</div>
        {current.status === 'interrupted' ? <div className="interrupted-actions"><button className="button resume" onClick={() => act(() => resumeTask(current))}><Play fill="currentColor" /> Resume now</button><button className="button reset-after-interruption" onClick={() => setReset({ task: current, fromInterruption: true, initialDuration: 1, startImmediately: true })}><RotateCcw /> Reset / Breathe</button></div> : <><div className="reset-quick-row"><button className="button reset-focus-button" onClick={() => setReset({ task: current, fromInterruption: false, startImmediately: true })}><RotateCcw /> Reset / Breathe</button><button className="reset-options" onClick={() => setReset({ task: current, fromInterruption: false, startImmediately: false })}>Options</button></div><div className="action-grid"><button className="button done" onClick={async()=>{await completeTask(current);setCelebration(current);refresh()}}><Check /> Done</button><button className="button soft" onClick={() => setModal('interrupt')}><CirclePause /> Interrupted</button><button className="button soft" onClick={() => setModal('block')}><Ban /> Blocked</button><button className="button soft" onClick={() => setModal('capture')}><Inbox /> Capture</button></div></>}
      </> : next ? <div className="empty-now"><Sparkles /><h2>{next.title}</h2><p>{next.estimatedMinutes} minutes · {next.category}</p><button className="button primary start" onClick={() => act(() => startTask(next.id))}><Play fill="currentColor" /> Start this task</button></div> : <div className="empty-now"><Sparkles /><h2>Nothing needs your attention.</h2><p>Add something in Plan, or enjoy the breathing room.</p></div>}
    </section>
    <section className="next-card"><div><p className="eyebrow">NEXT</p><h3>{current ? (next?.title ?? 'Nothing queued') : 'Shown after you start'}</h3></div>{current && next && <span>{next.estimatedMinutes} min</span>}</section>
    {!current&&<div className="reset-quick-row standalone"><button className="button reset-focus-button" onClick={()=>setReset({fromInterruption:false,startImmediately:true})}><RotateCcw/> Reset / Breathe</button><button className="reset-options" onClick={()=>setReset({fromInterruption:false,startImmediately:false})}>Options</button></div>}
    {!current && <button className="floating-capture" onClick={openCapture}><Inbox /> Capture a thought</button>}
    {modal && <Modal title={modal === 'capture' ? 'Quick capture' : modal === 'interrupt' ? 'Save your place' : 'What’s in the way?'} onClose={() => { setModal(null); setNote('') }}><form onSubmit={e => { e.preventDefault(); if (modal === 'capture') { if(note.trim()) act(() => addCapture(note.trim())) } else if (current) act(() => modal === 'interrupt' ? interruptTask(current, note) : blockTask(current, note)) }}><label>{modal === 'capture' ? 'Thought or item' : 'Short note (optional)'}<textarea autoFocus rows={4} value={note} onChange={e => setNote(e.target.value)} placeholder={modal === 'capture' ? 'Get it out of your head…' : 'A few words is enough…'} /></label><div className="form-actions"><button type="button" className="button ghost" onClick={() => setModal(null)}>Cancel</button><button className="button primary" type="submit">{modal === 'capture' ? 'Save & return' : modal === 'interrupt' ? 'Pause task' : 'Mark blocked'}</button></div></form></Modal>}
    {reset && <ResetExperience task={reset.task} fromInterruption={reset.fromInterruption} initialDuration={reset.initialDuration} startImmediately={reset.startImmediately} onCancel={() => setReset(undefined)} onResume={async () => { if (reset.fromInterruption&&reset.task) await resumeTask(reset.task); setReset(undefined); refresh() }} />}
    {celebration&&<CompletionCelebration task={celebration} onFinished={()=>setCelebration(undefined)}/>} 
  </main>
}
