import { useMemo, useState } from 'react'
import { CalendarDays, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Edit3, Flag, MoveRight, Plus, Trash2 } from 'lucide-react'
import { Modal } from '../components/Modal'
import { TaskForm, type TaskFormData } from '../components/TaskForm'
import type { Task } from '../types'
import { createWeeklyTask, dateKey, deleteWeeklyTask, moveTaskToDate, parseDateKey, reorderWeeklyTask, startOfWeek, updateWeeklyTask, weekDates } from '../weekService'

export function WeekView({ allTasks, refresh }: { allTasks: Task[]; refresh: () => void }) {
  const [anchor, setAnchor] = useState(startOfWeek()); const [selected, setSelected] = useState(dateKey(new Date())); const [editing, setEditing] = useState<Task | null | undefined>(undefined); const [moving, setMoving] = useState<Task>()
  const days = useMemo(() => weekDates(anchor), [anchor]); const selectedTasks = allTasks.filter(task => task.plannedDate === selected).sort((a,b)=>a.order-b.order); const today = dateKey(new Date())
  const shift = (weeks: number) => { const next = new Date(anchor); next.setDate(next.getDate() + weeks * 7); setAnchor(next); setSelected(dateKey(next)) }
  const save = async (data: TaskFormData) => { if (editing) await updateWeeklyTask(editing.id, data); else await createWeeklyTask(selected, data); setEditing(undefined); refresh() }
  const weekLabel = `${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(days[0])} – ${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(days[6])}`
  return <main className="page week-view"><div className="page-header"><div><p className="eyebrow">WEEK</p><h1>Plan where things belong.</h1><p>TODAY is for doing. WEEK is for planning.</p></div><button className="button primary" onClick={()=>setEditing(null)}><Plus/> Add task</button></div>
    <div className="week-controls"><button onClick={()=>shift(-1)} aria-label="Previous week"><ChevronLeft/></button><div><strong>{weekLabel}</strong><button onClick={()=>{const now=new Date();setAnchor(startOfWeek(now));setSelected(dateKey(now))}}>Current week</button></div><button onClick={()=>shift(1)} aria-label="Next week"><ChevronRight/></button></div>
    <div className="day-selector">{days.map(day=>{const key=dateKey(day);return <button key={key} className={`${selected===key?'selected ':''}${today===key?'today':''}`} onClick={()=>setSelected(key)}><span>{new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(day)}</span><strong>{day.getDate()}</strong>{today===key&&<small>Today</small>}</button>})}</div>
    <section className="selected-day"><div className="selected-day-heading"><div><p className="eyebrow">SELECTED DAY</p><h2>{new Intl.DateTimeFormat('en-US',{weekday:'long',month:'long',day:'numeric'}).format(parseDateKey(selected))}</h2></div><span>{selectedTasks.length} task{selectedTasks.length===1?'':'s'}</span></div>
      <div className="week-task-list">{selectedTasks.length?selectedTasks.map((task,index)=><article key={task.id}><div className="reorder"><button disabled={index===0} onClick={async()=>{await reorderWeeklyTask(selected,task,-1);refresh()}}><ChevronUp/></button><button disabled={index===selectedTasks.length-1} onClick={async()=>{await reorderWeeklyTask(selected,task,1);refresh()}}><ChevronDown/></button></div><div className="week-task-info"><div><strong>{task.title}</strong>{task.majorObjective&&<span className="major-badge"><Flag/> Major</span>}</div><small>{task.category} · {task.estimatedMinutes} min{task.plannedStart?` · around ${task.plannedStart}`:''}</small></div><button onClick={()=>setMoving(task)}><MoveRight/><span>Move</span></button><button onClick={()=>setEditing(task)} aria-label="Edit task"><Edit3/></button><button onClick={async()=>{if(confirm(`Delete “${task.title}”?`)){await deleteWeeklyTask(task);refresh()}}} aria-label="Delete task"><Trash2/></button></article>):<div className="empty-state"><CalendarDays/><h2>This day has room.</h2><p>Add a task here without adding clutter to TODAY.</p></div>}</div></section>
    {editing!==undefined&&<Modal title={editing?'Edit weekly task':'Add weekly task'} onClose={()=>setEditing(undefined)}><TaskForm task={editing??undefined} onSubmit={save} onCancel={()=>setEditing(undefined)} submitLabel={editing?'Save changes':'Add to this day'}/></Modal>}
    {moving&&<Modal title={`Move “${moving.title}”`} onClose={()=>setMoving(undefined)}><div className="move-day-list">{days.map(day=>{const key=dateKey(day);return <button disabled={key===moving.plannedDate} key={key} onClick={async()=>{await moveTaskToDate(moving,key);setMoving(undefined);setSelected(key);refresh()}}><span>{new Intl.DateTimeFormat('en-US',{weekday:'long'}).format(day)}</span><strong>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric'}).format(day)}</strong></button>})}</div></Modal>}
  </main>
}
